### PR TITLE
URL validation fixes

### PR DESCRIPTION
**Pull request by stegru**
* Trims whitespace from the url field
* Assumes urls found in the button catalog are working, and don't check them

Related: https://github.com/raisingthefloor/morphic-api-server/pull/113

### CODE REVIEW

**Review by christopher-rtf — CHANGES_REQUESTED** [review]
Two notes on accepting already-known-good URLs:

1. Why are we doing this?  Is it a core issue we're solving, or an attempt at a small optimization?

2. This code isn't complete.  It doesn't seem to account for case-insensitive matches.  Comparing "www.<hostname>" and "<hostname>" isn't correct both because www.example.com and example.com could be different sites and also because it would match matches like www.example.com and www.www.example.com.

code expression referred to in note #2:
(u.hostname === urlParsed.hostname || u.hostname === `www.${urlParsed.hostname}`) && u.pathname === urlParsed.pathname

**Comment by christopher-rtf** [comment]
Also, if we're doing URL matches generally:
- all components of the URL must match (scheme, hostname, path and query string); the part after the optional # may or may not matter, depending on the circumstance...so we could make that an optional match

For example, if we know that "https://onlyacceptssecureconnections.com" works but the user typed in "http://onlyacceptssecureconnections.com" then a failure to check the scheme potentially introduces a bug.

Similarly, if we know that "https://example.com?product=SKU123" works then a 'successful' match against "https://example.com?product=SKU456" could introduce a potential bug as well.

Unless there's a critical reason to create an optimization, it might be best to _not_ attempt this kind of optimization...unless it's thoroughly implemented and provides a significant- and critical-enough optimization to warrant its maintenance.

If we do leave the optimization/check in there...we need to thoroughly document why it's there, what it's meant to do, and what things we need to make sure we don't change elsewhere in the code (or at least what assumptions we're making about the rest of our codebase).

**Comment by stegru** [comment]
> 1. Why are we doing this?  Is it a core issue we're solving, or an attempt at a small optimization?

Mostly optimisation. I did that before fixing the API service, many of the sites were failing.

> 2. This code isn't complete.  It doesn't seem to account for case-insensitive matches.  Comparing "www." and "" isn't correct 

yes, it's crap.

**Comment by christopher-rtf** [comment]
> Mostly optimisation. I did that before fixing the API service, many of the sites were failing.

Let's go ahead and pull out the "existing known URLs" optimization then, and focus on making sure the API server code is taking care of the core issue instead.

**Review by christopher-rtf — CHANGES_REQUESTED** [review]
I'm still seeing "isKnown" in here.  It looks like it's not being initialized, but then gets compared against twice (including in one circumstance of an 'else' which didn't have such a qualification before)?

What am I missing?  Was that intentional...or just missed?

[Ideally once changes are made, we should check the "files changed" tab to double-check the composite changes for the PR.]

**Review by christopher-rtf — APPROVED** [review]

**Pull request merged**
