### PR TITLE
Side panel redesign

### PR DESCRIPTION
**Pull request by stegru**
Part of the **July Redesign 2021-07-27** section of  [SPEC - Morphic Plus Customization WebApp](https://docs.google.com/document/d/1l2u3Jn3liOXZFlWl9YIX33IyA_-jOZ0Fm1WlUtL0nwQ/edit#heading=h.kd6vtbpqdap2)

## Redesign of green side bar

* Updated the styling:
  * Changed colours.
  * Replaced the `+` and `-`  expander buttons with chevrons.
  * Added a :gear: member settings button.
* Changed the invitation status wording.
* Created a member details dialog.
* Changed the numbering for new bars to movie-sequel style, where duplicate names start from 2.
* Applied A11Y improvements raised from the latest feedback:
  * Removed bullets from spoken text
  * Added appropriate aria attributes
  * Expanding content correctly

new side panel design

member details dialog

### CODE REVIEW

**Review by christopher-rtf — CHANGES_REQUESTED** [review]
On the dashboard home page, the left pane is far too wide (at least on my monitor).

Is it set to the same width when the user is editing a bar?

We need the bar size to remain the same.

**Comment by stegru** [comment]
The panel is now the same size on the dashboard page, as it is on the editor page.

**Review by christopher-rtf — CHANGES_REQUESTED** [review]
The disclosure arrow should be changed from a triangle to a ^/v, to match the spec.

image

Also: the new bar ordering appears to still be appending "(1)" instead of "(2)" when a bar name is duplicated.  Please correct this.

image

**Comment by stegru** [comment]
now:
image

**Review by christopher-rtf — APPROVED** [review]
Thanks for getting those fixed, stegru :)

Merged.

**Pull request merged**
